### ISSUE TITLE
Exercise 5 uses currying without explaining

### ISSUE THREAD

**Issue by tejasbubane** [protoship/learn-reasonml-workshop#24]
https://github.com/protoship/learn-reasonml-workshop/blob/f3f320ef5cd5b4572b542ee2cdebaead174c46d2/src/exercises/05-twice/twice.re#L19-L23

Definition of `twice` takes 2 arguments but usage in `add2` takes only 1. This might be confusing for people unaware about the implicit currying.

**Comment by jasim** [comment]
@tejasbubane Will take a look. Thanks for the report!
