### ISSUE TITLE
Solutions of these exercises

### ISSUE THREAD

**Issue by rsimsek** [protoship/learn-reasonml-workshop#26]
Hi,

I am wondering if there are solutions for these exercises in a different repo that i can check with my own answers?

**Comment by fstiffo** [comment]
Not connected to your request, but answering to 
> How to add tuples ? Any help would be appreciated.  (sketch.sh)

`let add = ((x, y), (x', y')) => (x+x', y+y');`

**Comment by jcsherin** [comment]
@rsimsek Sorry, there is no other repo currently with solutions. I've responded to your [sketch here](https://sketch.sh/s/0bUZZnGg6i2CTQWXPo3PXD/)
